#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = ["pyyaml"]
# ///
"""
AgentWire Write Tool Damage Control
===================================

Claude Code PreToolUse hook for Write tool calls. Blocks writes to protected
files using the same shared rule set as the Bash and Edit hooks.

Implementation: the body of ``agentwire/safety/_core.py`` is inlined below
between the BEGIN/END GENERATED markers. Edit ``_core.py``, then run
``scripts/regen_damage_control_hooks.py`` — never edit between the markers.
"""

import json
import os
import sys
from pathlib import Path

try:
    from audit_logger import log_allowed, log_blocked
except ImportError:
    def log_allowed(*args, **kwargs): pass
    def log_blocked(*args, **kwargs): pass


# === BEGIN GENERATED FROM agentwire/safety/_core.py ===
"""
Shared damage-control logic for both the agentwire CLI (`agentwire safety check`)
and the Claude Code PreToolUse hooks (bash/edit/write).

Single source of truth. The hook scripts inline this file's contents at the time
they're regenerated by ``scripts/regen_damage_control_hooks.py``; do not let this
file drift from what's inlined. ``tests/unit/test_damage_control_sync.py`` will
fail loudly if drift happens.
"""

import fnmatch
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml
except ImportError:
    yaml = None


# ============================================================================
# CONSTANTS
# ============================================================================

ALL_OPERATIONS = {"read", "write", "edit", "delete", "move", "chmod"}

# Operation pattern tuples: (regex template with {path} placeholder, operation name).

WRITE_PATTERNS = [
    (r'>\s*{path}', "write"),
    (r'\btee\s+(?!.*-a).*{path}', "write"),
    (r'\bdd\s+.*\bof=\S*{path}', "write"),
    (r'\brsync\s+.*\s+{path}', "write"),
    (r'\btar\s+(-c|--create)\S*\s+.*{path}', "write"),
    (r'\binstall\s+.*\s+{path}', "write"),
]

APPEND_PATTERNS = [
    (r'>>\s*{path}', "append"),
    (r'\btee\s+-a\s+.*{path}', "append"),
    (r'\btee\s+.*-a.*{path}', "append"),
]

EDIT_PATTERNS = [
    (r'\bsed\s+-i.*{path}', "edit"),
    (r'\bperl\s+-[^\s]*i.*{path}', "edit"),
    (r'\bawk\s+-i\s+inplace.*{path}', "edit"),
]

MOVE_COPY_PATTERNS = [
    (r'\bmv\s+.*\s+{path}', "move"),
    (r'\bcp\s+.*\s+{path}', "copy"),
]

DELETE_PATTERNS = [
    (r'\brm\s+.*{path}', "delete"),
    (r'\bunlink\s+.*{path}', "delete"),
    (r'\brmdir\s+.*{path}', "delete"),
    (r'\bshred\s+.*{path}', "delete"),
]

PERMISSION_PATTERNS = [
    (r'\bchmod\s+.*{path}', "chmod"),
    (r'\bchown\s+.*{path}', "chown"),
    (r'\bchgrp\s+.*{path}', "chgrp"),
]

TRUNCATE_PATTERNS = [
    (r'\btruncate\s+.*{path}', "truncate"),
    (r':\s*>\s*{path}', "truncate"),
]

READ_ONLY_BLOCKED = (
    WRITE_PATTERNS
    + APPEND_PATTERNS
    + EDIT_PATTERNS
    + MOVE_COPY_PATTERNS
    + DELETE_PATTERNS
    + PERMISSION_PATTERNS
    + TRUNCATE_PATTERNS
)

NO_DELETE_BLOCKED = DELETE_PATTERNS


# ============================================================================
# GLOB / PATH HELPERS
# ============================================================================


def is_glob_pattern(pattern: str) -> bool:
    return '*' in pattern or '?' in pattern or '[' in pattern


def glob_to_regex(pattern: str) -> str:
    """Convert a glob to a regex usable inside command-line contexts.

    Trailing word-boundary check ensures e.g. ``*.py`` doesn't match
    ``foo.python``.
    """
    result = ""
    for char in pattern:
        if char == '*':
            result += r'[^\s/]*'
        elif char == '?':
            result += r'[^\s/]'
        elif char in r'\.^$+{}[]|()':
            result += '\\' + char
        else:
            result += char
    result += r'(?![a-zA-Z0-9_])'
    return result


def matches_path_in_command(pattern: str, command: str) -> bool:
    """Check if a path pattern occurs in a command string in a path-context."""
    expanded = os.path.expanduser(pattern)
    if not is_glob_pattern(pattern):
        return expanded in command

    glob_regex = glob_to_regex(expanded)
    file_path_regex = r'(?:^|[\s/="\'<>])' + glob_regex + r'(?:[\s"\')<>]|$)'
    try:
        if not re.search(file_path_regex, command, re.IGNORECASE):
            return False
    except re.error:
        return False

    # Reject method-call lookalikes: foo.py( should not match *.py
    extension = pattern.split('*')[-1] if '*' in pattern else pattern
    if extension.startswith('.'):
        extension = extension[1:]
    if extension and re.search(r'\w\.' + re.escape(extension) + r'\s*\(', command):
        return False
    return True


def match_path(file_path: str, pattern: str) -> bool:
    """Match a single absolute file path against a pattern (glob or prefix)."""
    expanded_pattern = os.path.expanduser(pattern)
    normalized = os.path.normpath(file_path)
    expanded_normalized = os.path.expanduser(normalized)
    if is_glob_pattern(pattern):
        lower_path = expanded_normalized.lower()
        lower_pattern = expanded_pattern.lower()
        if fnmatch.fnmatch(lower_path, lower_pattern):
            return True
        basename = os.path.basename(expanded_normalized)
        if fnmatch.fnmatch(basename.lower(), lower_pattern):
            return True
        return False
    return (
        expanded_normalized.startswith(expanded_pattern)
        or expanded_normalized == expanded_pattern.rstrip('/')
    )


def _parse_allowed_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize an allowed-paths entry to ``{path: str, allow: set}``."""
    allow = entry.get("allow", "all")
    if isinstance(allow, str) and allow.strip().lower() == "all":
        return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}
    if isinstance(allow, list):
        return {"path": entry["path"], "allow": {a.strip().lower() for a in allow}}
    if isinstance(allow, str):
        return {"path": entry["path"], "allow": {allow.strip().lower()}}
    return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}


def _find_project_config() -> Tuple[str, List[Any]]:
    """Walk up from $PWD to find ``.agentwire.yml`` and return its allowed_paths."""
    cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        config_file = os.path.join(current, ".agentwire.yml")
        if os.path.isfile(config_file):
            try:
                if yaml:
                    with open(config_file, "r") as f:
                        data = yaml.safe_load(f) or {}
                    safety = data.get("safety", {})
                    if isinstance(safety, dict):
                        paths = safety.get("allowed_paths", [])
                        if isinstance(paths, list):
                            return current, paths
            except Exception:
                pass
            return current, []
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return cwd, []


def load_allowed_paths(config: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Merge global ``allowedPaths`` from config with per-project ``.agentwire.yml`` entries."""
    raw = list(config.get("allowedPaths", []))

    project_root, project_paths = _find_project_config()
    for p in project_paths:
        if not isinstance(p, dict):
            continue
        entry = _parse_allowed_entry(p)
        if not os.path.isabs(os.path.expanduser(entry["path"])):
            entry["path"] = os.path.join(project_root, entry["path"])
        raw.append(entry)

    result = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        if "allow" in item and isinstance(item["allow"], set):
            result.append(item)
        else:
            result.append(_parse_allowed_entry(item))
    return result


def is_path_allowed_for_op(
    file_path: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str,
) -> bool:
    """Check if ``file_path`` has ``operation`` permitted by some allowed-path entry."""
    for entry in allowed_paths:
        if match_path(file_path, entry["path"]):
            if operation in entry["allow"]:
                return True
    return False


def _extract_command_paths(command: str) -> List[str]:
    """Extract file/directory paths from a bash command string."""
    paths = []
    for m in re.finditer(r'''["']([^"']+)["']''', command):
        candidate = m.group(1)
        if '/' in candidate or candidate.startswith('.'):
            paths.append(os.path.expanduser(candidate))
    for token in re.split(r'\s+', command):
        token = token.strip("\"'")
        if token.startswith(('/', '~/', './')):
            paths.append(os.path.expanduser(token))
        elif '/' in token and not token.startswith('-'):
            paths.append(os.path.expanduser(token))
    return paths


def is_command_path_allowed(
    command: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str = "write",
) -> bool:
    """ALL paths in ``command`` must have ``operation`` permitted by allowlist.

    Security: ALL paths must match (not any) — this stops e.g.
    ``rm /tmp/safe.txt /etc/passwd`` from being allowed just because /tmp is
    allowlisted.
    """
    if not allowed_paths:
        return False
    paths = _extract_command_paths(command)
    if not paths:
        return False
    for p in paths:
        if not is_path_allowed_for_op(p, allowed_paths, operation):
            return False
    return True


def _infer_operation_from_reason(reason: str) -> str:
    """Map a pattern's reason text back to one of the allowlist operation names."""
    reason_lower = reason.lower()
    if (
        "rm" in reason_lower
        or "delet" in reason_lower
        or "trash" in reason_lower
        or "rmdir" in reason_lower
    ):
        return "delete"
    if "chmod" in reason_lower or "permission" in reason_lower:
        return "chmod"
    if "chown" in reason_lower or "chgrp" in reason_lower:
        return "chmod"
    if "mv" in reason_lower or "move" in reason_lower:
        return "move"
    return "write"


def check_path_patterns(
    command: str,
    path: str,
    patterns: List[Tuple[str, str]],
    path_type: str,
) -> Tuple[bool, str]:
    """Check if any operation pattern matches ``command`` targeting ``path``.

    Returns ``(matched, reason)`` where reason names the operation that triggered.
    """
    if is_glob_pattern(path):
        path_regex = glob_to_regex(path)
    else:
        expanded = os.path.expanduser(path)
        if expanded == path:
            path_regex = re.escape(path)
        else:
            path_regex = r'(?:' + re.escape(expanded) + r'|' + re.escape(path) + r')'

    for pattern_template, operation in patterns:
        try:
            full_pattern = pattern_template.replace("{path}", path_regex)
            if re.search(full_pattern, command, re.IGNORECASE):
                return True, f"{operation} operation on {path_type} {path}"
        except re.error:
            continue
    return False, ""


# ============================================================================
# CONFIG LOADING
# ============================================================================


def _cmd_to_regex(cmd: str) -> Optional[str]:
    """Convert a tooldef command string to a regex matching its fixed prefix.

    Stops at the first flag (- or --), placeholder (<...>), or optional ([...]).
    Example: ``gws gmail +send --to <addr>`` -> ``\\bgws\\s+gmail\\s+\\+send\\b``
    """
    tokens = cmd.strip().split()
    fixed = []
    for token in tokens:
        if token.startswith('<') or token.startswith('[') or token.startswith('-'):
            break
        fixed.append(token)
    if not fixed:
        return None
    parts = [re.escape(t) for t in fixed]
    pattern = r'\b' + r'\s+'.join(parts)
    last = fixed[-1]
    if last and (last[-1].isalnum() or last[-1] == '_'):
        pattern += r'\b'
    return pattern


def load_write_patterns_from_tooldefs(tooldefs_dir: Optional[Path]) -> List[Dict[str, Any]]:
    """Generate ``ask:true`` patterns from write-tier commands in tooldef YAMLs."""
    if not yaml:
        return []
    patterns: List[Dict[str, Any]] = []
    if not tooldefs_dir or not tooldefs_dir.exists():
        return patterns
    for tf_file in sorted(tooldefs_dir.glob("*.yaml")):
        try:
            with open(tf_file, "r") as f:
                data = yaml.safe_load(f) or {}
            tool_name = data.get("name", tf_file.stem)
            for cmd_def in data.get("commands", []):
                if cmd_def.get("access") != "write":
                    continue
                cmd_str = cmd_def.get("cmd", "")
                regex = _cmd_to_regex(cmd_str)
                if not regex:
                    continue
                patterns.append({
                    "pattern": regex,
                    "reason": f"{tool_name}: {cmd_def.get('description', cmd_str)}",
                    "ask": True,
                })
        except Exception:
            continue
    return patterns


def load_config(
    rules_dir: Path,
    tooldefs_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """Load and merge all rule YAMLs in ``rules_dir`` plus tooldef ask-patterns."""
    merged: Dict[str, Any] = {
        "bashToolPatterns": [],
        "zeroAccessPaths": [],
        "readOnlyPaths": [],
        "noDeletePaths": [],
        "allowedPaths": [],
    }
    if not yaml or not rules_dir.exists():
        return merged
    yaml_files = sorted(rules_dir.glob("*.yaml"))
    for rules_file in yaml_files:
        try:
            with open(rules_file, "r") as f:
                data = yaml.safe_load(f) or {}
            for key in merged:
                merged[key].extend(data.get(key, []))
        except Exception:
            continue
    if tooldefs_dir is not None:
        merged["bashToolPatterns"].extend(
            load_write_patterns_from_tooldefs(tooldefs_dir)
        )
    return merged


# ============================================================================
# DECISION LADDERS
# ============================================================================


def check_command(command: str, config: Dict[str, Any]) -> Dict[str, Any]:
    """Decide whether a bash command should be allowed/blocked/asked.

    Returns ``{decision, reason, pattern, command}``.

    Order:
      1. Hard-blocked bash patterns (no ``bypassable`` flag) → BLOCK
      2. Ask patterns → ASK
      3. Bypassable bash patterns → check allowlist for required operation
      4. zeroAccessPaths → check allowlist with ``read`` permission
      5. readOnlyPaths → match against READ_ONLY_BLOCKED operation patterns
      6. noDeletePaths → match against NO_DELETE_BLOCKED patterns
    """
    bash_patterns = config.get("bashToolPatterns", [])
    zero_access = config.get("zeroAccessPaths", [])
    read_only = config.get("readOnlyPaths", [])
    no_delete = config.get("noDeletePaths", [])
    allowed = load_allowed_paths(config)

    bypassable_matches: List[Tuple[str, str]] = []

    for pattern_obj in bash_patterns:
        if not isinstance(pattern_obj, dict):
            continue
        pattern = pattern_obj.get("pattern", "")
        reason = pattern_obj.get("reason", "Matched pattern")
        should_ask = pattern_obj.get("ask", False)
        bypassable = pattern_obj.get("bypassable", False)
        try:
            if re.search(pattern, command, re.IGNORECASE):
                if should_ask:
                    return {
                        "decision": "ask",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                    }
                elif bypassable:
                    bypassable_matches.append((pattern, reason))
                else:
                    return {
                        "decision": "block",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                    }
        except re.error:
            continue

    for pattern, reason in bypassable_matches:
        operation = _infer_operation_from_reason(reason)
        if not is_command_path_allowed(command, allowed, operation):
            return {
                "decision": "block",
                "reason": reason,
                "pattern": pattern,
                "command": command,
            }

    for path in zero_access:
        if matches_path_in_command(path, command):
            if is_command_path_allowed(command, allowed, "read"):
                continue
            return {
                "decision": "block",
                "reason": f"Zero-access path: {path}",
                "pattern": f"zeroAccessPath: {path}",
                "command": command,
            }

    for path in read_only:
        matched, reason = check_path_patterns(command, path, READ_ONLY_BLOCKED, "read-only path")
        if matched:
            op = _infer_operation_from_reason(reason)
            if is_command_path_allowed(command, allowed, op):
                continue
            return {
                "decision": "block",
                "reason": f"Read-only path: {path}",
                "pattern": f"readOnlyPath: {path}",
                "command": command,
            }

    for path in no_delete:
        matched, _reason = check_path_patterns(command, path, NO_DELETE_BLOCKED, "no-delete path")
        if matched:
            if is_command_path_allowed(command, allowed, "delete"):
                continue
            return {
                "decision": "block",
                "reason": f"No-delete path: {path}",
                "pattern": f"noDeletePath: {path}",
                "command": command,
            }

    return {
        "decision": "allow",
        "reason": "No patterns matched",
        "pattern": None,
        "command": command,
    }


def check_path(file_path: str, config: Dict[str, Any]) -> Tuple[bool, str]:
    """File-path-only check used by edit/write hooks. Returns ``(blocked, reason)``."""
    allowed = load_allowed_paths(config)

    if is_path_allowed_for_op(file_path, allowed, "edit"):
        return False, ""

    for zero_path in config.get("zeroAccessPaths", []):
        if match_path(file_path, zero_path):
            return True, f"zero-access path {zero_path} (no operations allowed)"

    for readonly in config.get("readOnlyPaths", []):
        if match_path(file_path, readonly):
            return True, f"read-only path {readonly}"

    return False, ""
# === END GENERATED ===


# ============================================================================
# HOOK ENTRY POINT
# ============================================================================


def _resolve_rules_dir() -> Path:
    user_dir = Path(os.environ.get("AGENTWIRE_DIR", os.path.expanduser("~/.agentwire")))
    user_rules = user_dir / "damage-control"
    if user_rules.exists() and any(user_rules.glob("*.yaml")):
        return user_rules
    return Path(__file__).parent / "rules"


def main() -> None:
    config = load_config(_resolve_rules_dir())

    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON input: {e}", file=sys.stderr)
        sys.exit(1)

    tool_name = input_data.get("tool_name", "")
    tool_input = input_data.get("tool_input", {})

    if tool_name != "Write":
        sys.exit(0)

    file_path = tool_input.get("file_path", "")
    if not file_path:
        sys.exit(0)

    blocked, reason = check_path(file_path, config)
    if blocked:
        log_blocked("Write", file_path, reason)
        print(f"SECURITY: Blocked write to {reason}: {file_path}", file=sys.stderr)
        sys.exit(2)

    log_allowed("Write", file_path, user_approved=False)
    sys.exit(0)


if __name__ == "__main__":
    main()
